/*
 * File:           Z:\Sigmastudio teh DSP\system files\teh_DSP_IC_1_PARAM.h
 *
 * Created:        Friday, October 22, 2021 8:33:43 AM
 * Description:    teh_DSP:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2021 Analog Devices, Inc. All rights reserved.
 */
#ifndef __TEH_DSP_IC_1_PARAM_H__
#define __TEH_DSP_IC_1_PARAM_H__


/* Module Input mute ADC - Mute*/
#define MOD_INPUTMUTEADC_COUNT                         2
#define MOD_INPUTMUTEADC_DEVICE                        "IC1"
#define MOD_INPUTMUTEADC_ALG0_MUTEONOFF_ADDR           0
#define MOD_INPUTMUTEADC_ALG0_MUTEONOFF_FIXPT          0x00800000
#define MOD_INPUTMUTEADC_ALG0_MUTEONOFF_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUTMUTEADC_ALG0_MUTEONOFF_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUTMUTEADC_ALG0_STEP_ADDR                1
#define MOD_INPUTMUTEADC_ALG0_STEP_FIXPT               0x00002000
#define MOD_INPUTMUTEADC_ALG0_STEP_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0009765625)
#define MOD_INPUTMUTEADC_ALG0_STEP_TYPE                SIGMASTUDIOTYPE_FIXPOINT

/* Module Input mute I2S - Mute*/
#define MOD_INPUTMUTEI2S_COUNT                         2
#define MOD_INPUTMUTEI2S_DEVICE                        "IC1"
#define MOD_INPUTMUTEI2S_ALG0_MUTEONOFF_ADDR           2
#define MOD_INPUTMUTEI2S_ALG0_MUTEONOFF_FIXPT          0x00800000
#define MOD_INPUTMUTEI2S_ALG0_MUTEONOFF_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUTMUTEI2S_ALG0_MUTEONOFF_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUTMUTEI2S_ALG0_STEP_ADDR                3
#define MOD_INPUTMUTEI2S_ALG0_STEP_FIXPT               0x00002000
#define MOD_INPUTMUTEI2S_ALG0_STEP_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0009765625)
#define MOD_INPUTMUTEI2S_ALG0_STEP_TYPE                SIGMASTUDIOTYPE_FIXPOINT

/* Module Input mixer - Stereo Mixer*/
#define MOD_INPUTMIXER_COUNT                           2
#define MOD_INPUTMIXER_DEVICE                          "IC1"
#define MOD_INPUTMIXER_ALG0_STAGE0_VOLUME_ADDR         4
#define MOD_INPUTMIXER_ALG0_STAGE0_VOLUME_FIXPT        0x00800000
#define MOD_INPUTMIXER_ALG0_STAGE0_VOLUME_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUTMIXER_ALG0_STAGE0_VOLUME_TYPE         SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUTMIXER_ALG0_STAGE1_VOLUME_ADDR         5
#define MOD_INPUTMIXER_ALG0_STAGE1_VOLUME_FIXPT        0x00800000
#define MOD_INPUTMIXER_ALG0_STAGE1_VOLUME_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUTMIXER_ALG0_STAGE1_VOLUME_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module DC block - DC Blocking*/
#define MOD_DCBLOCK_COUNT                              2
#define MOD_DCBLOCK_DEVICE                             "IC1"
#define MOD_DCBLOCK_ALG0_DCBLOCKALGDOUBLEPREC1POLE_ADDR 6
#define MOD_DCBLOCK_ALG0_DCBLOCKALGDOUBLEPREC1POLE_FIXPT 0x007FFCB9
#define MOD_DCBLOCK_ALG0_DCBLOCKALGDOUBLEPREC1POLE_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCBLOCK_ALG0_DCBLOCKALGDOUBLEPREC1POLE_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DCBLOCK_ALG1_DCBLOCKALGDOUBLEPREC2POLE_ADDR 7
#define MOD_DCBLOCK_ALG1_DCBLOCKALGDOUBLEPREC2POLE_FIXPT 0x007FFCB9
#define MOD_DCBLOCK_ALG1_DCBLOCKALGDOUBLEPREC2POLE_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCBLOCK_ALG1_DCBLOCKALGDOUBLEPREC2POLE_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Crossover main/sub - Crossover*/
#define MOD_CROSSOVERMAINSUB_COUNT                     84
#define MOD_CROSSOVERMAINSUB_DEVICE                    "IC1"
#define MOD_CROSSOVERMAINSUB_ALG0_CROSSOVERFILTER2WAYALGDP1LOWINVERT_ADDR 8
#define MOD_CROSSOVERMAINSUB_ALG0_CROSSOVERFILTER2WAYALGDP1LOWINVERT_FIXPT 0x00800000
#define MOD_CROSSOVERMAINSUB_ALG0_CROSSOVERFILTER2WAYALGDP1LOWINVERT_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CROSSOVERMAINSUB_ALG0_CROSSOVERFILTER2WAYALGDP1LOWINVERT_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_CROSSOVERFILTER2WAYALGDP1LOWINVERT_ADDR 8
#define MOD_CROSSOVERMAINSUB_ALG0_CROSSOVERFILTER2WAYALGDP1LOWINVERT_FIXPT 0x00800000
#define MOD_CROSSOVERMAINSUB_ALG0_CROSSOVERFILTER2WAYALGDP1LOWINVERT_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CROSSOVERMAINSUB_ALG0_CROSSOVERFILTER2WAYALGDP1LOWINVERT_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB0_ADDR 9
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB0_FIXPT 0x00000102
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.08180684457864E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB0_ADDR 9
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB0_FIXPT 0x00000102
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.08180684457864E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB1_ADDR 10
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB1_FIXPT 0x00000205
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(6.16361368915727E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB1_ADDR 10
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB1_FIXPT 0x00000205
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(6.16361368915727E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA1_ADDR 11
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA1_FIXPT 0x00FEE61A
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99139717342186)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA1_ADDR 11
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA1_FIXPT 0x00FEE61A
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99139717342186)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB2_ADDR 12
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB2_FIXPT 0x00000102
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.08180684457864E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB2_ADDR 12
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB2_FIXPT 0x00000102
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.08180684457864E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA2_ADDR 13
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA2_FIXPT 0xFF8115DC
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.991520445695647)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA2_ADDR 13
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA2_FIXPT 0xFF8115DC
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.991520445695647)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT1_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB0_ADDR 14
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB0_FIXPT 0x00000100
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.06343861872037E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB0_ADDR 14
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB0_FIXPT 0x00000100
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.06343861872037E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB1_ADDR 15
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB1_FIXPT 0x00000201
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(6.12687723744074E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB1_ADDR 15
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB1_FIXPT 0x00000201
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(6.12687723744074E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA1_ADDR 16
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA1_FIXPT 0x00FD612C
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.9795280216873)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA1_ADDR 16
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA1_FIXPT 0x00FD612C
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.9795280216873)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB2_ADDR 17
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB2_FIXPT 0x00000100
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.06343861872037E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB2_ADDR 17
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB2_FIXPT 0x00000100
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.06343861872037E-05)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA2_ADDR 18
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA2_FIXPT 0xFF829AD0
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.979650559232049)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA2_ADDR 18
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA2_FIXPT 0xFF829AD0
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.979650559232049)
#define MOD_CROSSOVERMAINSUB_ALG0_LOW_FILT2_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB0_ADDR 19
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB0_FIXPT 0x007F4279
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994216173058527)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB0_ADDR 19
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB0_FIXPT 0x007F4279
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994216173058527)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB1_ADDR 20
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB1_FIXPT 0xFF017B0D
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.98843234611705)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB1_ADDR 20
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB1_FIXPT 0xFF017B0D
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.98843234611705)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA1_ADDR 21
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA1_FIXPT 0x00FE8142
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98831969378849)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA1_ADDR 21
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA1_FIXPT 0x00FE8142
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98831969378849)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB2_ADDR 22
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB2_FIXPT 0x007F4279
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994216173058527)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB2_ADDR 22
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB2_FIXPT 0x007F4279
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994216173058527)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA2_ADDR 23
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA2_FIXPT 0xFF81775C
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.988544998445615)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA2_ADDR 23
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA2_FIXPT 0xFF81775C
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.988544998445615)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT1_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB0_ADDR 24
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB0_FIXPT 0x007E3CB6
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986227817212055)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB0_ADDR 24
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB0_FIXPT 0x007E3CB6
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986227817212055)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB1_ADDR 25
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB1_FIXPT 0xFF038693
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.97245563442411)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB1_ADDR 25
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB1_FIXPT 0xFF038693
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.97245563442411)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA1_ADDR 26
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA1_FIXPT 0x00FC75C3
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.97234388723762)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA1_ADDR 26
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA1_FIXPT 0x00FC75C3
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.97234388723762)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB2_ADDR 27
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB2_FIXPT 0x007E3CB6
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986227817212055)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB2_ADDR 27
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB2_FIXPT 0x007E3CB6
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986227817212055)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA2_ADDR 28
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA2_FIXPT 0xFF8382EA
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.972567381610599)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA2_ADDR 28
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA2_FIXPT 0xFF8382EA
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.972567381610599)
#define MOD_CROSSOVERMAINSUB_ALG0_HIGH_FILT2_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_CROSSOVERFILTER2WAYALGDP2LOWINVERT_ADDR 29
#define MOD_CROSSOVERMAINSUB_ALG1_CROSSOVERFILTER2WAYALGDP2LOWINVERT_FIXPT 0x00800000
#define MOD_CROSSOVERMAINSUB_ALG1_CROSSOVERFILTER2WAYALGDP2LOWINVERT_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CROSSOVERMAINSUB_ALG1_CROSSOVERFILTER2WAYALGDP2LOWINVERT_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_CROSSOVERFILTER2WAYALGDP2LOWINVERT_ADDR 29
#define MOD_CROSSOVERMAINSUB_ALG1_CROSSOVERFILTER2WAYALGDP2LOWINVERT_FIXPT 0x00800000
#define MOD_CROSSOVERMAINSUB_ALG1_CROSSOVERFILTER2WAYALGDP2LOWINVERT_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CROSSOVERMAINSUB_ALG1_CROSSOVERFILTER2WAYALGDP2LOWINVERT_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB0_ADDR 30
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB0_FIXPT 0x00000102
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.08180684457864E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB0_ADDR 30
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB0_FIXPT 0x00000102
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.08180684457864E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB1_ADDR 31
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB1_FIXPT 0x00000205
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(6.16361368915727E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB1_ADDR 31
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB1_FIXPT 0x00000205
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(6.16361368915727E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA1_ADDR 32
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA1_FIXPT 0x00FEE61A
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99139717342186)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA1_ADDR 32
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA1_FIXPT 0x00FEE61A
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99139717342186)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB2_ADDR 33
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB2_FIXPT 0x00000102
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.08180684457864E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB2_ADDR 33
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB2_FIXPT 0x00000102
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.08180684457864E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA2_ADDR 34
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA2_FIXPT 0xFF8115DC
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.991520445695647)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA2_ADDR 34
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA2_FIXPT 0xFF8115DC
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.991520445695647)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT1_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB0_ADDR 35
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB0_FIXPT 0x00000100
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.06343861872037E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB0_ADDR 35
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB0_FIXPT 0x00000100
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.06343861872037E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB1_ADDR 36
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB1_FIXPT 0x00000201
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(6.12687723744074E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB1_ADDR 36
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB1_FIXPT 0x00000201
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(6.12687723744074E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA1_ADDR 37
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA1_FIXPT 0x00FD612C
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.9795280216873)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA1_ADDR 37
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA1_FIXPT 0x00FD612C
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.9795280216873)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB2_ADDR 38
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB2_FIXPT 0x00000100
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.06343861872037E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB2_ADDR 38
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB2_FIXPT 0x00000100
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.06343861872037E-05)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA2_ADDR 39
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA2_FIXPT 0xFF829AD0
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.979650559232049)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA2_ADDR 39
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA2_FIXPT 0xFF829AD0
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.979650559232049)
#define MOD_CROSSOVERMAINSUB_ALG1_LOW_FILT2_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB0_ADDR 40
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB0_FIXPT 0x007F4279
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994216173058527)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB0_ADDR 40
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB0_FIXPT 0x007F4279
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994216173058527)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB1_ADDR 41
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB1_FIXPT 0xFF017B0D
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.98843234611705)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB1_ADDR 41
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB1_FIXPT 0xFF017B0D
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.98843234611705)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA1_ADDR 42
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA1_FIXPT 0x00FE8142
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98831969378849)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA1_ADDR 42
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA1_FIXPT 0x00FE8142
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98831969378849)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB2_ADDR 43
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB2_FIXPT 0x007F4279
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994216173058527)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB2_ADDR 43
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB2_FIXPT 0x007F4279
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994216173058527)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA2_ADDR 44
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA2_FIXPT 0xFF81775C
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.988544998445615)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA2_ADDR 44
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA2_FIXPT 0xFF81775C
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.988544998445615)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT1_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB0_ADDR 45
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB0_FIXPT 0x007E3CB6
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986227817212055)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB0_ADDR 45
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB0_FIXPT 0x007E3CB6
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986227817212055)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB1_ADDR 46
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB1_FIXPT 0xFF038693
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.97245563442411)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB1_ADDR 46
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB1_FIXPT 0xFF038693
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.97245563442411)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA1_ADDR 47
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA1_FIXPT 0x00FC75C3
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.97234388723762)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA1_ADDR 47
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA1_FIXPT 0x00FC75C3
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.97234388723762)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB2_ADDR 48
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB2_FIXPT 0x007E3CB6
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986227817212055)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB2_ADDR 48
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB2_FIXPT 0x007E3CB6
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986227817212055)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMB2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA2_ADDR 49
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA2_FIXPT 0xFF8382EA
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.972567381610599)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA2_ADDR 49
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA2_FIXPT 0xFF8382EA
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.972567381610599)
#define MOD_CROSSOVERMAINSUB_ALG1_HIGH_FILT2_PARAMA2_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Main inv L - Signal Invert*/
#define MOD_MAININVL_COUNT                             1
#define MOD_MAININVL_DEVICE                            "IC1"
#define MOD_MAININVL_EQ1940INVERT1GAIN_ADDR            50
#define MOD_MAININVL_EQ1940INVERT1GAIN_FIXPT           0x00800000
#define MOD_MAININVL_EQ1940INVERT1GAIN_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MAININVL_EQ1940INVERT1GAIN_TYPE            SIGMASTUDIOTYPE_FIXPOINT

/* Module Main inv R - Signal Invert*/
#define MOD_MAININVR_COUNT                             1
#define MOD_MAININVR_DEVICE                            "IC1"
#define MOD_MAININVR_EQ1940INVERT2GAIN_ADDR            51
#define MOD_MAININVR_EQ1940INVERT2GAIN_FIXPT           0x00800000
#define MOD_MAININVR_EQ1940INVERT2GAIN_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MAININVR_EQ1940INVERT2GAIN_TYPE            SIGMASTUDIOTYPE_FIXPOINT

/* Module Sub inv R - Signal Invert*/
#define MOD_SUBINVR_COUNT                              1
#define MOD_SUBINVR_DEVICE                             "IC1"
#define MOD_SUBINVR_EQ1940INVERT4GAIN_ADDR             52
#define MOD_SUBINVR_EQ1940INVERT4GAIN_FIXPT            0x00800000
#define MOD_SUBINVR_EQ1940INVERT4GAIN_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SUBINVR_EQ1940INVERT4GAIN_TYPE             SIGMASTUDIOTYPE_FIXPOINT

/* Module Sub inv L - Signal Invert*/
#define MOD_SUBINVL_COUNT                              1
#define MOD_SUBINVL_DEVICE                             "IC1"
#define MOD_SUBINVL_EQ1940INVERT3GAIN_ADDR             53
#define MOD_SUBINVL_EQ1940INVERT3GAIN_FIXPT            0x00800000
#define MOD_SUBINVL_EQ1940INVERT3GAIN_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SUBINVL_EQ1940INVERT3GAIN_TYPE             SIGMASTUDIOTYPE_FIXPOINT

/* Module Main HP - General (2nd order)*/
#define MOD_MAINHP_COUNT                               5
#define MOD_MAINHP_DEVICE                              "IC1"
#define MOD_MAINHP_ALG0_STAGE0_B0_ADDR                 54
#define MOD_MAINHP_ALG0_STAGE0_B0_FIXPT                0x00800000
#define MOD_MAINHP_ALG0_STAGE0_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MAINHP_ALG0_STAGE0_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINHP_ALG0_STAGE0_B1_ADDR                 55
#define MOD_MAINHP_ALG0_STAGE0_B1_FIXPT                0x00000000
#define MOD_MAINHP_ALG0_STAGE0_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MAINHP_ALG0_STAGE0_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINHP_ALG0_STAGE0_B2_ADDR                 56
#define MOD_MAINHP_ALG0_STAGE0_B2_FIXPT                0x00000000
#define MOD_MAINHP_ALG0_STAGE0_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MAINHP_ALG0_STAGE0_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINHP_ALG0_STAGE0_A1_ADDR                 57
#define MOD_MAINHP_ALG0_STAGE0_A1_FIXPT                0x00000000
#define MOD_MAINHP_ALG0_STAGE0_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MAINHP_ALG0_STAGE0_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINHP_ALG0_STAGE0_A2_ADDR                 58
#define MOD_MAINHP_ALG0_STAGE0_A2_FIXPT                0x00000000
#define MOD_MAINHP_ALG0_STAGE0_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MAINHP_ALG0_STAGE0_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT

/* Module Sub HP - General (2nd order)*/
#define MOD_SUBHP_COUNT                                5
#define MOD_SUBHP_DEVICE                               "IC1"
#define MOD_SUBHP_ALG0_STAGE0_B0_ADDR                  59
#define MOD_SUBHP_ALG0_STAGE0_B0_FIXPT                 0x00800000
#define MOD_SUBHP_ALG0_STAGE0_B0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SUBHP_ALG0_STAGE0_B0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBHP_ALG0_STAGE0_B1_ADDR                  60
#define MOD_SUBHP_ALG0_STAGE0_B1_FIXPT                 0x00000000
#define MOD_SUBHP_ALG0_STAGE0_B1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SUBHP_ALG0_STAGE0_B1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBHP_ALG0_STAGE0_B2_ADDR                  61
#define MOD_SUBHP_ALG0_STAGE0_B2_FIXPT                 0x00000000
#define MOD_SUBHP_ALG0_STAGE0_B2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SUBHP_ALG0_STAGE0_B2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBHP_ALG0_STAGE0_A1_ADDR                  62
#define MOD_SUBHP_ALG0_STAGE0_A1_FIXPT                 0x00000000
#define MOD_SUBHP_ALG0_STAGE0_A1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SUBHP_ALG0_STAGE0_A1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBHP_ALG0_STAGE0_A2_ADDR                  63
#define MOD_SUBHP_ALG0_STAGE0_A2_FIXPT                 0x00000000
#define MOD_SUBHP_ALG0_STAGE0_A2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SUBHP_ALG0_STAGE0_A2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Main LP - General (2nd order)*/
#define MOD_MAINLP_COUNT                               5
#define MOD_MAINLP_DEVICE                              "IC1"
#define MOD_MAINLP_ALG0_STAGE0_B0_ADDR                 64
#define MOD_MAINLP_ALG0_STAGE0_B0_FIXPT                0x00800000
#define MOD_MAINLP_ALG0_STAGE0_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MAINLP_ALG0_STAGE0_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINLP_ALG0_STAGE0_B1_ADDR                 65
#define MOD_MAINLP_ALG0_STAGE0_B1_FIXPT                0x00000000
#define MOD_MAINLP_ALG0_STAGE0_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MAINLP_ALG0_STAGE0_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINLP_ALG0_STAGE0_B2_ADDR                 66
#define MOD_MAINLP_ALG0_STAGE0_B2_FIXPT                0x00000000
#define MOD_MAINLP_ALG0_STAGE0_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MAINLP_ALG0_STAGE0_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINLP_ALG0_STAGE0_A1_ADDR                 67
#define MOD_MAINLP_ALG0_STAGE0_A1_FIXPT                0x00000000
#define MOD_MAINLP_ALG0_STAGE0_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MAINLP_ALG0_STAGE0_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINLP_ALG0_STAGE0_A2_ADDR                 68
#define MOD_MAINLP_ALG0_STAGE0_A2_FIXPT                0x00000000
#define MOD_MAINLP_ALG0_STAGE0_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MAINLP_ALG0_STAGE0_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT

/* Module Sub LP - General (2nd order)*/
#define MOD_SUBLP_COUNT                                5
#define MOD_SUBLP_DEVICE                               "IC1"
#define MOD_SUBLP_ALG0_STAGE0_B0_ADDR                  69
#define MOD_SUBLP_ALG0_STAGE0_B0_FIXPT                 0x00800000
#define MOD_SUBLP_ALG0_STAGE0_B0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SUBLP_ALG0_STAGE0_B0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBLP_ALG0_STAGE0_B1_ADDR                  70
#define MOD_SUBLP_ALG0_STAGE0_B1_FIXPT                 0x00000000
#define MOD_SUBLP_ALG0_STAGE0_B1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SUBLP_ALG0_STAGE0_B1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBLP_ALG0_STAGE0_B2_ADDR                  71
#define MOD_SUBLP_ALG0_STAGE0_B2_FIXPT                 0x00000000
#define MOD_SUBLP_ALG0_STAGE0_B2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SUBLP_ALG0_STAGE0_B2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBLP_ALG0_STAGE0_A1_ADDR                  72
#define MOD_SUBLP_ALG0_STAGE0_A1_FIXPT                 0x00000000
#define MOD_SUBLP_ALG0_STAGE0_A1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SUBLP_ALG0_STAGE0_A1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBLP_ALG0_STAGE0_A2_ADDR                  73
#define MOD_SUBLP_ALG0_STAGE0_A2_FIXPT                 0x00000000
#define MOD_SUBLP_ALG0_STAGE0_A2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SUBLP_ALG0_STAGE0_A2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Main bypass - Stereo Switch Nx2*/
#define MOD_MAINBYPASS_COUNT                           1
#define MOD_MAINBYPASS_DEVICE                          "IC1"
#define MOD_MAINBYPASS_STEREOSWSLEW_ADDR               74
#define MOD_MAINBYPASS_STEREOSWSLEW_FIXPT              0x00000000
#define MOD_MAINBYPASS_STEREOSWSLEW_VALUE              SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_MAINBYPASS_STEREOSWSLEW_TYPE               SIGMASTUDIOTYPE_INTEGER

/* Module Sub bypass - Stereo Switch Nx2*/
#define MOD_SUBBYPASS_COUNT                            1
#define MOD_SUBBYPASS_DEVICE                           "IC1"
#define MOD_SUBBYPASS_STEREOSWSLEW_ADDR                75
#define MOD_SUBBYPASS_STEREOSWSLEW_FIXPT               0x00000000
#define MOD_SUBBYPASS_STEREOSWSLEW_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_SUBBYPASS_STEREOSWSLEW_TYPE                SIGMASTUDIOTYPE_INTEGER

/* Module Master volume main - Single SW slew vol (adjustable)*/
#define MOD_MASTERVOLUMEMAIN_COUNT                     2
#define MOD_MASTERVOLUMEMAIN_DEVICE                    "IC1"
#define MOD_MASTERVOLUMEMAIN_ALG0_TARGET_ADDR          76
#define MOD_MASTERVOLUMEMAIN_ALG0_TARGET_FIXPT         0x00800000
#define MOD_MASTERVOLUMEMAIN_ALG0_TARGET_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MASTERVOLUMEMAIN_ALG0_TARGET_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MASTERVOLUMEMAIN_ALG0_STEP_ADDR            77
#define MOD_MASTERVOLUMEMAIN_ALG0_STEP_FIXPT           0x00000800
#define MOD_MASTERVOLUMEMAIN_ALG0_STEP_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_MASTERVOLUMEMAIN_ALG0_STEP_TYPE            SIGMASTUDIOTYPE_FIXPOINT

/* Module Master volume sub - Single SW slew vol (adjustable)*/
#define MOD_MASTERVOLUMESUB_COUNT                      2
#define MOD_MASTERVOLUMESUB_DEVICE                     "IC1"
#define MOD_MASTERVOLUMESUB_ALG0_TARGET_ADDR           78
#define MOD_MASTERVOLUMESUB_ALG0_TARGET_FIXPT          0x00800000
#define MOD_MASTERVOLUMESUB_ALG0_TARGET_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MASTERVOLUMESUB_ALG0_TARGET_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MASTERVOLUMESUB_ALG0_STEP_ADDR             79
#define MOD_MASTERVOLUMESUB_ALG0_STEP_FIXPT            0x00000800
#define MOD_MASTERVOLUMESUB_ALG0_STEP_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_MASTERVOLUMESUB_ALG0_STEP_TYPE             SIGMASTUDIOTYPE_FIXPOINT

/* Module Main mute - Mute*/
#define MOD_MAINMUTE_COUNT                             2
#define MOD_MAINMUTE_DEVICE                            "IC1"
#define MOD_MAINMUTE_ALG0_MUTEONOFF_ADDR               80
#define MOD_MAINMUTE_ALG0_MUTEONOFF_FIXPT              0x00800000
#define MOD_MAINMUTE_ALG0_MUTEONOFF_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MAINMUTE_ALG0_MUTEONOFF_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MAINMUTE_ALG0_STEP_ADDR                    81
#define MOD_MAINMUTE_ALG0_STEP_FIXPT                   0x00002000
#define MOD_MAINMUTE_ALG0_STEP_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0009765625)
#define MOD_MAINMUTE_ALG0_STEP_TYPE                    SIGMASTUDIOTYPE_FIXPOINT

/* Module Sub level - Single SW slew vol (adjustable)*/
#define MOD_SUBLEVEL_COUNT                             2
#define MOD_SUBLEVEL_DEVICE                            "IC1"
#define MOD_SUBLEVEL_ALG0_TARGET_ADDR                  82
#define MOD_SUBLEVEL_ALG0_TARGET_FIXPT                 0x00040C37
#define MOD_SUBLEVEL_ALG0_TARGET_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0316227766016838)
#define MOD_SUBLEVEL_ALG0_TARGET_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBLEVEL_ALG0_STEP_ADDR                    83
#define MOD_SUBLEVEL_ALG0_STEP_FIXPT                   0x00000800
#define MOD_SUBLEVEL_ALG0_STEP_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SUBLEVEL_ALG0_STEP_TYPE                    SIGMASTUDIOTYPE_FIXPOINT

/* Module Sub mute - Mute*/
#define MOD_SUBMUTE_COUNT                              2
#define MOD_SUBMUTE_DEVICE                             "IC1"
#define MOD_SUBMUTE_ALG0_MUTEONOFF_ADDR                84
#define MOD_SUBMUTE_ALG0_MUTEONOFF_FIXPT               0x00800000
#define MOD_SUBMUTE_ALG0_MUTEONOFF_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SUBMUTE_ALG0_MUTEONOFF_TYPE                SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SUBMUTE_ALG0_STEP_ADDR                     85
#define MOD_SUBMUTE_ALG0_STEP_FIXPT                    0x00002000
#define MOD_SUBMUTE_ALG0_STEP_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0009765625)
#define MOD_SUBMUTE_ALG0_STEP_TYPE                     SIGMASTUDIOTYPE_FIXPOINT

#endif
